export default {
  LOAD_TASKS: 'LOAD_TASKS',
  ADD_TASK: 'ADD_TASK',
  DELETE_TASK: 'DELETE_TASK',
  DONE_TASK: 'DONE_TASK',

  LOAD_TASKS_ERROR: 'LOAD_TASKS_ERROR',
  ADD_TASKS_ERROR: 'ADD_TASKS_ERROR',
  DELETE_TASKS_ERROR: 'DELETE_TASKS_ERROR',
  DONE_TASKS_ERROR: 'DONE_TASKS_ERROR',
};
