export default {
  LOAD_TASKS: 'LOAD_TASKS',
  LOAD_TASKS_ERROR: 'LOAD_TASKS_ERROR',
  DELETE_TASK: 'DELETE_TASK',
  DELETE_TASK_ERROR: 'DELETE_TASK_ERROR',
  ADD_TASK: 'ADD_TASK',
  ADD_TASK_ERROR: 'ADD_TASK_ERROR',
  COMPLETE_TASK: 'COMPLETE_TASK',
  COMPLETE_TASK_ERROR: 'COMPLETE_TASK_ERROR',
  UPDATE_TASK: 'UPDATE_TASK',
  UPDATE_TASK_ERROR: 'UPDATE_TASK_ERROR',
};
