export default {
  AUTH_LOGIN: 'AUTH_LOGIN',
  AUTH_LOGOUT: 'AUTH_LOGOUT',
  LOAD_USER: 'LOAD_USER',
  LOAD_ERROR: 'LOAD_ERROR',
  DELETE_ERROR: 'DELETE_ERROR',
  LOAD_PRODUCTS: 'LOAD_PRODUCTS',
  LOAD_CART: 'LOAD_CART',
  ADD_PRODUCT: 'ADD_PRODUCT',
  DELETE_PRODUCT: 'DELETE_PRODUCT'
};
