export default {
  LOAD_HEROES: 'LOAD_HEROES',
  DELETE_HERO: 'DELETE_HERO',
  ADD_HERO: 'ADD_HERO',
  UPDATE_HERO: 'UPDATE_HERO',

  LOAD_HERO: 'LOAD_HERO',
  LOAD_HEROES_ERROR: 'LOAD_HEROES_ERROR',
};
