const actionTypes = {
  LOAD_PRODUCTS: 'LOAD_PRODUCTS',
  BUY_PRODUCTS: 'BUY_PRODUCTS',
  ADD_TO_CART: 'ADD_TO_CART',
  REMOVE_FROM_CART: 'REMOVE_FROM_CART',
  REMOVE_ALL_FROM_CART: 'REMOVE_ALL_FROM_CART',
};

export default actionTypes;
