export default {
  LOAD_PRODUCT: 'LOAD_PRODUCT',
  ADD_PRODUCTS_TO_CART: 'ADD_PRODUCTS_TO_CART',
  LOAD_CART_PRODUCT: 'LOAD_CART_PRODUCT',
  LOAD_PRODUCT_ERROR: 'LOAD_PRODUCT_ERROR,',
  DELETE_CART_PRODUCT: 'DELETE_CART_PRODUCT',
  UPDATE_PRODUCTS: 'UPDATE_PRODUCTS'
};
