export default {
  AUTH_LOGIN: 'AUTH_LOGIN',
  AUTH_LOGOUT: 'AUTH_LOGOUT',
  LOAD_MOVIES: 'LOAD_MOVIES',
  LOAD_TITLE_MOST_VIEWED: 'LOAD_TITLE',
  LOAD_TITLE_LAST_RELEASES: 'LOAD_TITLE_LAST_RELEASES',
  LOAD_TITLE_MOST_VALUED: 'LOAD_TITLE_MOST_VALUED',
  LOAD_GENRE_MOVIE: 'LOAD_GENRE_MOVIE',
  LOAD_MOVIE: 'LOAD_MOVIE',
  LOAD_CAST: 'LOAD_CAST',
  LOAD_RECOMENDED: 'LOAD_RECOMENDED',
  LOAD_SHOWS: 'LOAD_SHOWS'
};
