export default {
  AUTH_LOGIN: 'AUTH_LOGIN',
  AUTH_LOGOUT: 'AUTH_LOGOUT',
  LOAD_MOVIES: 'LOAD_MOVIES',
  LOAD_GENRE_MOVIE: 'LOAD_GENRE_MOVIE',
  LOAD_MOVIE: 'LOAD_MOVIE',
  LOAD_CAST: 'LOAD_CAST',
  LOAD_RECOMENDED: 'LOAD_RECOMENDED',
  LOAD_SHOWS: 'LOAD_SHOWS',
  LOAD_GRID_MOVIES: 'LOAD_GRID_MOVIES',
  LOAD_SHOW: 'LOAD_SHOW',
  LOAD_SHOWS_RECOMMENDED: 'LOAD_SHOWS_RECOMMENDED'
};
