export default {
  LOAD_GLOBAL: 'LOAD_GLOBAL',
  LOAD_COUNTRY: 'LOAD_COUNTRY',
  LOAD_VACCINES_MAP: 'LOAD_VACCINES_MAP',
  LOAD_VACCINES_BY_COUNTRY: 'LOAD_VACCINES_BY_COUNTRY',
  LOAD_VACCINES_BY_CONTINENT: 'LOAD_VACCINES_BY_CONTINENT',
  AUTH_LOGIN: 'AUTH_LOGIN',
  AUTH_LOGOUT: 'AUTH_LOGOUT'
};
