// CRUD
const CREATE_TASK = 'CREATE_TASK';
const SHOW_EDIT_TASK_BUTTON = 'SHOW_EDIT_TASK_BUTTON';
const EDIT_TASK = 'EDIT_TASK';
const DELETE_TASK = 'DELETE_TASK';
const MARK_AS_DONE = 'MARK_AS_DONE';
