const actionTypes = {
  ADD_USER: 'ADD_USER',
  AUTH_LOGIN: 'AUTH_LOGIN',
  AUTH_LOGOUT: 'AUTH_LOGOUT',
  CHANGE_FACTION: 'CHANGE_FACTION',
  CREATE_TRAVEL: 'CREATE_TRAVEL',
  DELETE_WISH: 'DELETE_WISH',
  LOAD_LOCAL_CHARACTERS: 'LOAD_LOCAL_CHARACTERS',
  LOAD_LOCAL_PLANETS: 'LOAD_LOCAL_PLANETS',
  LOAD_LOCAL_STARSHIPS: 'LOAD_LOCAL_STARSHIPS',
  LOAD_PEOPLE: 'LOAD_PEOPLE',
  LOAD_PLANETS: 'LOAD_PLANETS',
  LOAD_STARSHIPS: 'LOAD_STARSHIPS',
  LOAD_WISHLIST: 'LOAD_WISHLIST',
  LOAD_SWAPI: 'LOAD_SWAPI',
  MODIFY_USERNAME: 'MODIFY_USERNAME',
  MODIFY_WISH: 'MODIFY_WISH',
  RESET_PROFILE: 'RESET_PROFILE',
  SELECT_AVATAR: 'SELECT_AVATAR',
  SET_CURRENT_PLANET: 'SET_CURRENT_PLANET',
  SET_CURRENT_STARSHIP: 'SET_CURRENT_STARSHIP',
  SHOW_PRICE: 'SHOW_PRICE'
};

export default actionTypes;
