const actionTypes = {
  ADD_USER: 'ADD_USER',
  DELETE_WISH: 'DELETE_WISH',
  CHANGE_FACTION: 'CHANGE_FACTION',
  LOAD_LOCAL_CHARACTERS: 'LOAD_LOCAL_CHARACTERS',
  LOAD_LOCAL_PLANETS: 'LOAD_LOCAL_PLANETS',
  LOAD_LOCAL_STARSHIPS: 'LOAD_LOCAL_STARSHIPS',
  LOAD_PEOPLE: 'LOAD_PEOPLE',
  LOAD_PLANETS: 'LOAD_PLANETS',
  LOAD_STARSHIPS: 'LOAD_STARSHIPS',
  LOAD_SWAPI: 'LOAD_SWAPI',
  MODIFY_USERNAME: 'MODIFY_USERNAME',
  MODIFY_WISH: 'MODIFY_WISH',
  RESET_PROFILE: 'RESET_PROFILE',
  SELECT_AVATAR: 'SELECT_AVATAR',
  SELECT_FACTION: 'SELECT_FACTION',
  SELECT_PLANET: 'SELECT_SPACESHIP',
  SHOW_DETAILS: 'SHOW_DETAILS',
  SHOW_PRICE: 'SHOW_PRICE'
};

export default actionTypes;
