export default {
  LOAD_ARTWORKS: 'LOAD_ARTWORKS',
  LOAD_CATEGORY: 'LOAD_CATEGORY',
  LOAD_DETAIL: 'LOAD_DETAIL',
  AUTH_LOGIN: 'AUTH_LOGIN',
  AUTH_LOGOUT: 'AUTH_LOGOUT',
  LOAD_ERROR: 'LOAD_ERROR',
};
