export default {
  LOAD_ARTWORKS: 'LOAD_ARTWORKS',
  LOAD_FAVORITES: 'LOAD_FAVORITES',
  DELETE_FAVORITE: 'DELETE_FAVORITE',
  ADD_FAVORITE: 'ADD_FAVORITE',
  LOAD_CATEGORY: 'LOAD_CATEGORY',
  LOAD_DETAIL: 'LOAD_DETAIL',
  AUTH_LOGIN: 'AUTH_LOGIN',
  AUTH_LOGOUT: 'AUTH_LOGOUT',
};
