export default {
  LOAD_TASKS: 'LOAD_TASKS',
  ADD_TASK: 'CREATE_TASK',
  DELETE_TASK: 'DELETE_TASK',
  UPDATE_TASK: 'UPDATE_TASK',
  LOAD_TASKS_ERROR: 'LOAD_TASKS_ERROR',
  ADD_TASK_ERROR: 'CREATE_TASK_ERROR',
  DELETE_TASK_ERROR: 'DELETE_TASK_ERROR',
  UPDATE_TASK_ERROR: 'UPDATE_TASK_ERROR',
};
